// SPDX-License-Identifier: BSD-2-Clause
// This code was generated by `SqlHydra.Sqlite` -- v4.0.0-beta.3.
namespace ConfigDb

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 0, 0)
    let ns = "ConfigDb"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type build = { key: Option<string>; value: string }

    [<CLIMutable>]
    type project =
        { name: Option<string>
          repo: string
          license: string
          submod: Option<string> }

    [<CLIMutable>]
    type substrate =
        { name: Option<string>
          resource: string
          ref_left: string
          ref_right: string
          domain: Option<string> }

    [<CLIMutable>]
    type tool =
        { name: Option<string>
          path: Option<string>
          version: Option<string>
          required: Option<int64> }


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
