// SPDX-License-Identifier: BSD-2-Clause
// Copyright (c) 2026 Rajeshkumar Venugopal / Third Buyer Advisory
//
// gen_config_module.fsx — generate C++26 module from config.db
//
// Reads build table from config.db, emits src/config/config.cppm
// with constexpr values. Clang compiles it. All C++ code imports it.
// Zero magic numbers in C++ source.
//
// Usage: dotnet fsi scripts/gen_config_module.fsx -- config.db src/config/config.cppm

#r "nuget: Microsoft.Data.Sqlite, 9.0.4"
open System
open System.IO
open Microsoft.Data.Sqlite

let args = fsi.CommandLineArgs |> Array.skip 1
if args.Length < 2 then
    eprintfn "Usage: dotnet fsi scripts/gen_config_module.fsx -- <config.db> <output.cppm>"
    exit 1

let dbPath = args.[0]
let outPath = args.[1]

if not (File.Exists dbPath) then
    eprintfn "config.db not found at %s. Run: cmake -S . -B build" dbPath
    exit 1

let conn = new SqliteConnection(sprintf "Data Source=%s;Mode=ReadOnly" dbPath)
conn.Open()

// Read all build keys
let rows = ResizeArray<string * string>()
use cmd = conn.CreateCommand()
cmd.CommandText <- "SELECT key, value FROM build ORDER BY key"
use reader = cmd.ExecuteReader()
while reader.Read() do
    rows.Add(reader.GetString(0), reader.GetString(1))
conn.Close()

// Classify values: hex, int, or string
let isHex (v: string) = v.StartsWith("0x") || v.StartsWith("0X")
let isInt (v: string) = v |> Seq.forall (fun c -> Char.IsDigit c || c = '-')

// Generate C++26 module
Directory.CreateDirectory(Path.GetDirectoryName(outPath)) |> ignore

let lines = ResizeArray<string>()
lines.Add("// SPDX-License-Identifier: BSD-2-Clause")
lines.Add("// Generated by gen_config_module.fsx from config.db — do not edit")
lines.Add("//")
lines.Add("// Every constant comes from config.db. Change the db, regenerate.")
lines.Add("// Zero magic numbers in C++ source.")
lines.Add("")
lines.Add("export module rp4.config;")
lines.Add("import std;")
lines.Add("")
lines.Add("export namespace rp4::config {")
lines.Add("")

for (key, value) in rows do
    let cppName = key  // already snake_case from db
    if isHex value then
        lines.Add(sprintf "    inline constexpr std::uintptr_t %s = %s;" cppName value)
    elif isInt value then
        let n = int64 value
        if n > int64 Int32.MaxValue then
            lines.Add(sprintf "    inline constexpr std::size_t %s = %sUL;" cppName value)
        else
            lines.Add(sprintf "    inline constexpr int %s = %s;" cppName value)
    else
        lines.Add(sprintf "    inline constexpr const char* %s = \"%s\";" cppName value)

lines.Add("")
lines.Add("} // namespace rp4::config")
lines.Add("")

File.WriteAllLines(outPath, lines)

printfn "  generated: %s (%d constants from %d db rows)" outPath (rows.Count) (rows.Count)
